import type {
  CriticalVariable, ThresholdAlert, FormulaVersion,
  HistoricEvent, AuditEntry, DataQualityIssue
} from './types';

// Current simulated state (NE = 383.6 m.s.n.m.)
export const CURRENT_NE = 383.6;
export const CURRENT_DATE = '19/05/2026';
export const CURRENT_TIME = '08:42';

// Formula evaluation helpers
export const calcThresholdSE = (ne: number) => 4e-13 * Math.exp(0.0563 * ne) + 58.49;
export const calcThresholdE0 = (ne: number) => 4e-13 * Math.exp(0.0563 * ne) + 116.98;

const NE_TREND = [381.2, 381.8, 382.3, 382.9, 383.1, 383.4, 383.6, 383.6, 383.5, 383.6, 383.6, 383.5];
const DATES_TREND = ['07/05','08/05','09/05','10/05','11/05','12/05','13/05','14/05','15/05','16/05','17/05','19/05'];

export const VARIABLES: CriticalVariable[] = [
  {
    id: 'v1',
    code: 'AUS-Q-FT-001',
    name: 'Filtración Total',
    sensor_code: 'CAU-FT-001',
    sensor_type: 'Caudalímetro',
    unit: 'lts/min',
    current_value: 212.7,
    current_ne: CURRENT_NE,
    source: 'DAMDATA',
    last_reading: `${CURRENT_DATE} ${CURRENT_TIME}`,
    status: 'extraordinary',
    recommended_action: 'Confirmación de Situación Extraordinaria por Director/a de Explotación. Activar vigilancia intensificada.',
    formula_se: 'Q > 4×10⁻¹³ × exp(0,0563 × NE) + 58,49',
    formula_e0: 'Q > 4×10⁻¹³ × exp(0,0563 × NE) + 116,98',
    threshold_se: calcThresholdSE(CURRENT_NE),
    threshold_e0: calcThresholdE0(CURRENT_NE),
    is_blocked: false,
    has_manual_data: false,
    trend: [82.3, 103.8, 128.9, 162.4, 183.1, 171.6, 198.4, 202.1, 208.3, 211.5, 212.7, 212.7],
    trend_dates: DATES_TREND,
    ne_trend: NE_TREND,
  },
  {
    id: 'v2',
    code: 'AUS-PI-014',
    name: 'Presión Intersticial P-14',
    sensor_code: 'PIEZ-014',
    sensor_type: 'Piezómetro',
    unit: 'm.c.a.',
    current_value: 34.2,
    current_ne: CURRENT_NE,
    source: 'DAMDATA',
    last_reading: `${CURRENT_DATE} ${CURRENT_TIME}`,
    status: 'normal',
    recommended_action: 'Sin acción requerida. Continuar monitorización periódica.',
    formula_se: 'H > 40,0',
    formula_e0: 'H > 50,0',
    threshold_se: 40.0,
    threshold_e0: 50.0,
    is_blocked: false,
    has_manual_data: false,
    trend: [22.1, 23.5, 25.8, 27.2, 29.1, 30.3, 31.8, 32.4, 33.1, 33.8, 34.0, 34.2],
    trend_dates: DATES_TREND,
    ne_trend: NE_TREND,
  },
  {
    id: 'v3',
    code: 'AUS-TH-003',
    name: 'Temperatura Hormigón',
    sensor_code: 'TERM-003',
    sensor_type: 'Termómetro',
    unit: '°C',
    current_value: 18.4,
    current_ne: null,
    source: 'DAMDATA',
    last_reading: `${CURRENT_DATE} 07:30`,
    status: 'normal',
    recommended_action: 'Sin acción requerida.',
    formula_se: 'T > 28,0 o T < 5,0',
    formula_e0: 'T > 35,0',
    threshold_se: 28.0,
    threshold_e0: 35.0,
    is_blocked: false,
    has_manual_data: false,
    trend: [12.1, 12.8, 13.5, 14.2, 15.1, 15.9, 16.8, 17.1, 17.6, 18.0, 18.2, 18.4],
    trend_dates: DATES_TREND,
    ne_trend: NE_TREND,
  },
  {
    id: 'v4',
    code: 'AUS-DR-008',
    name: 'Caudal Drenaje Galería',
    sensor_code: 'DREN-008',
    sensor_type: 'Caudalímetro',
    unit: 'lts/min',
    current_value: 45.1,
    current_ne: CURRENT_NE,
    source: 'DAMDATA',
    last_reading: `${CURRENT_DATE} ${CURRENT_TIME}`,
    status: 'normal',
    recommended_action: 'Sin acción requerida.',
    formula_se: 'QD > 80,0',
    formula_e0: 'QD > 120,0',
    threshold_se: 80.0,
    threshold_e0: 120.0,
    is_blocked: false,
    has_manual_data: false,
    trend: [28.1, 31.2, 33.5, 36.8, 38.1, 39.5, 41.2, 42.1, 43.5, 44.1, 44.8, 45.1],
    trend_dates: DATES_TREND,
    ne_trend: NE_TREND,
  },
  {
    id: 'v5',
    code: 'AUS-INC-002',
    name: 'Desplazamiento Horizontal',
    sensor_code: 'INC-002',
    sensor_type: 'Inclinómetro',
    unit: 'mm',
    current_value: 2.8,
    current_ne: null,
    source: 'DAMDATA',
    last_reading: `${CURRENT_DATE} 06:00`,
    status: 'normal',
    recommended_action: 'Sin acción requerida.',
    formula_se: 'D > 5,0',
    formula_e0: 'D > 8,0',
    threshold_se: 5.0,
    threshold_e0: 8.0,
    is_blocked: false,
    has_manual_data: false,
    trend: [1.2, 1.5, 1.8, 2.0, 2.1, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.8],
    trend_dates: DATES_TREND,
    ne_trend: NE_TREND,
  },
  {
    id: 'v6',
    code: 'AUS-NE-SAIH',
    name: 'Nivel de Embalse',
    sensor_code: 'SAIH-NE',
    sensor_type: 'Pluviómetro',
    unit: 'm.s.n.m.',
    current_value: CURRENT_NE,
    current_ne: null,
    source: 'SAIH',
    last_reading: `${CURRENT_DATE} ${CURRENT_TIME}`,
    status: 'normal',
    recommended_action: 'Monitorización continua. Dato utilizado como variable dependiente en cálculos de umbral.',
    formula_se: 'NE > 388,0 (NAP)',
    formula_e0: 'NE > 390,0',
    threshold_se: 388.0,
    threshold_e0: 390.0,
    is_blocked: false,
    has_manual_data: false,
    trend: NE_TREND,
    trend_dates: DATES_TREND,
    ne_trend: NE_TREND,
  },
];

export const ALERTS: ThresholdAlert[] = [
  {
    id: 'a1',
    date: '19/05/2026 08:43',
    variable_id: 'v1',
    variable_name: 'Filtración Total',
    measured_value: 212.7,
    threshold_value: calcThresholdSE(CURRENT_NE),
    formula: 'Q > 4×10⁻¹³ × exp(0,0563 × 383,6) + 58,49 = 169,1',
    proposed_status: 'extraordinary',
    recipient: 'Director/a de Explotación',
    alert_status: 'pending',
    emergency_comm_sent: false,
  },
  {
    id: 'a2',
    date: '06/05/2026 10:08',
    variable_id: 'v1',
    variable_name: 'Filtración Total',
    measured_value: 198.4,
    threshold_value: calcThresholdSE(383.5),
    formula: 'Q > 4×10⁻¹³ × exp(0,0563 × 383,5) + 58,49 = 168,7',
    proposed_status: 'extraordinary',
    recipient: 'Director/a de Explotación',
    alert_status: 'confirmed',
    decision_user: 'Adm. SIPRESAS (Director/a)',
    decision_date: '06/05/2026 11:30',
    decision_reason: 'Situación Extraordinaria confirmada. Seguimiento diario activado. PEP no activado.',
    emergency_comm_sent: false,
  },
  {
    id: 'a3',
    date: '15/04/2026 10:05',
    variable_id: 'v1',
    variable_name: 'Filtración Total',
    measured_value: 183.1,
    threshold_value: calcThresholdSE(383.2),
    formula: 'Q > 4×10⁻¹³ × exp(0,0563 × 383,2) + 58,49 = 166,2',
    proposed_status: 'extraordinary',
    recipient: 'Director/a de Explotación',
    alert_status: 'rejected',
    decision_user: 'Adm. SIPRESAS (Director/a)',
    decision_date: '15/04/2026 17:00',
    decision_reason: 'Lectura puntual. Valores posteriores descendentes. No se confirma S.E.',
    emergency_comm_sent: false,
  },
];

export const FORMULA_VERSIONS: FormulaVersion[] = [
  {
    version: 3,
    formula_se: 'Q > 4×10⁻¹³ × exp(0,0563 × NE) + 58,49',
    formula_e0: 'Q > 4×10⁻¹³ × exp(0,0563 × NE) + 116,98',
    user: 'Técnico Auscultación',
    date: '10/01/2026',
    reason: 'Revisión Norma de Explotación 2026. Ajuste de coeficientes por análisis estadístico serie histórica.',
    approved: true,
  },
  {
    version: 2,
    formula_se: 'Q > 4×10⁻¹³ × exp(0,0563 × NE) + 62,00',
    formula_e0: 'Q > 4×10⁻¹³ × exp(0,0563 × NE) + 124,00',
    user: 'Técnico Auscultación',
    date: '15/03/2023',
    reason: 'Actualización tras inspección de seguridad 2023.',
    approved: true,
  },
  {
    version: 1,
    formula_se: 'Q > 150,0 (umbral fijo)',
    formula_e0: 'Q > 250,0 (umbral fijo)',
    user: 'Admin SIPRESAS',
    date: '01/01/2020',
    reason: 'Configuración inicial.',
    approved: true,
  },
];

export const HISTORIC_EVENTS: HistoricEvent[] = [
  { id: 'h1',  date: '19/05/2026', time: '08:42', variable: 'Filtración Total',    event_type: 'data_received',           user: 'DAMDATA',                    result: 'Q=212,7 lts/min',              reason: 'Sincronización automática' },
  { id: 'h2',  date: '19/05/2026', time: '08:42', variable: 'Filtración Total',    event_type: 'threshold_calculated',    user: 'Sistema SIPRESAS',           result: 'SE superada (umbral 169,1)',    reason: 'NE=383,6 m.s.n.m. (SAIH)' },
  { id: 'h3',  date: '19/05/2026', time: '08:43', variable: 'Filtración Total',    event_type: 'extraordinary_detected',  user: 'Sistema SIPRESAS',           result: 'Aviso generado',               reason: 'Q > umbral SE' },
  { id: 'h4',  date: '19/05/2026', time: '08:43', variable: 'Filtración Total',    event_type: 'alert_sent',              user: 'Sistema SIPRESAS',           result: 'Pendiente validación',         reason: 'Notificación a Director/a' },
  { id: 'h5',  date: '06/05/2026', time: '11:30', variable: 'Filtración Total',    event_type: 'manual_validation',       user: 'Director/a Explotación',     result: 'S.E. Confirmada',              reason: 'Vigilancia diaria activada' },
  { id: 'h6',  date: '06/05/2026', time: '10:08', variable: 'Filtración Total',    event_type: 'extraordinary_detected',  user: 'Sistema SIPRESAS',           result: 'Aviso enviado',                reason: 'Q=198,4 > umbral 168,7' },
  { id: 'h7',  date: '15/04/2026', time: '17:00', variable: 'Filtración Total',    event_type: 'activation_rejected',     user: 'Director/a Explotación',     result: 'S.E. Rechazada',               reason: 'Lectura puntual, no confirmada' },
  { id: 'h8',  date: '15/04/2026', time: '10:05', variable: 'Filtración Total',    event_type: 'extraordinary_detected',  user: 'Sistema SIPRESAS',           result: 'Aviso enviado',                reason: 'Q=183,1 > umbral 166,2' },
  { id: 'h9',  date: '10/01/2026', time: '09:15', variable: 'Filtración Total',    event_type: 'formula_modified',        user: 'Técnico Auscultación',       result: 'Versión 3 activa',             reason: 'Revisión NE 2026' },
  { id: 'h10', date: '20/03/2026', time: '14:22', variable: 'Caudal Drenaje',      event_type: 'data_incoherent',         user: 'Sistema SIPRESAS',           result: 'Dato marcado incoherente',     reason: 'Valor 0,0 lts/min (sensor fallo)' },
  { id: 'h11', date: '20/03/2026', time: '15:05', variable: 'Caudal Drenaje',      event_type: 'manual_data_entry',       user: 'Técnico Auscultación',       result: 'Valor manual 32,1 lts/min',    reason: 'Confirmado por inspección visual' },
];

export const AUDIT_ENTRIES: AuditEntry[] = [
  { id: 'au1',  date: '19/05/2026', time: '08:42', action: 'Consulta DAMDATA',            user: 'Sistema SIPRESAS',           result: 'OK — 6 variables recibidas',          reason: 'Sincronización periódica (5 min)',   hash: 'sha256:3f2a8b1c...' },
  { id: 'au2',  date: '19/05/2026', time: '08:42', action: 'Consulta SAIH',               user: 'Sistema SIPRESAS',           result: 'OK — NE=383,6 m.s.n.m.',             reason: 'Variable dependiente NE',           hash: 'sha256:9d1e4f7a...' },
  { id: 'au3',  date: '19/05/2026', time: '08:42', action: 'Cálculo expresión matemática', user: 'Sistema SIPRESAS',           result: 'SE superada — Q=212,7 > 169,1',      reason: 'Evaluación umbral AUS-Q-FT-001',    hash: 'sha256:1b5c9e2d...' },
  { id: 'au4',  date: '19/05/2026', time: '08:43', action: 'Aviso generado',              user: 'Sistema SIPRESAS',           result: 'Aviso #a1 pendiente validación',      reason: 'S.E. detectada AUS-Q-FT-001',       hash: 'sha256:7f3a2c8e...' },
  { id: 'au5',  date: '06/05/2026', time: '11:30', action: 'Aviso confirmado',            user: 'Director/a Explotación',     result: 'S.E. confirmada — vigilancia diaria', reason: 'Decisión Director/a',               hash: 'sha256:4e2b9f1c...' },
  { id: 'au6',  date: '15/04/2026', time: '17:00', action: 'Activación rechazada',        user: 'Director/a Explotación',     result: 'S.E. rechazada — no confirmada',      reason: 'Lectura puntual descendente',        hash: 'sha256:2c7d5a3f...' },
  { id: 'au7',  date: '10/01/2026', time: '09:15', action: 'Fórmula modificada',          user: 'Técnico Auscultación',       result: 'Versión 3 activa — aprobada',         reason: 'Revisión NE 2026',                  hash: 'sha256:8a1e6b4d...' },
  { id: 'au8',  date: '20/03/2026', time: '14:22', action: 'Dato marcado incoherente',    user: 'Sistema SIPRESAS',           result: 'Dato bloqueado para cálculo',         reason: 'DREN-008: valor 0,0 (fallo sensor)', hash: 'sha256:5f9c2a7e...' },
  { id: 'au9',  date: '20/03/2026', time: '15:05', action: 'Dato manual introducido',     user: 'Técnico Auscultación',       result: 'Valor 32,1 lts/min — validado',       reason: 'Inspección visual in situ',          hash: 'sha256:3b6d8f1a...' },
];

export const DATA_QUALITY_ISSUES: DataQualityIssue[] = [
  {
    id: 'dq1',
    variable_id: 'v4',
    variable_name: 'Caudal Drenaje Galería',
    issue_type: 'incoherent',
    original_value: 0.0,
    corrected_value: 32.1,
    user: 'Técnico Auscultación',
    date: '20/03/2026 15:05',
    reason: 'Sensor DREN-008 con fallo eléctrico temporal. Valor 0,0 incoherente con contexto. Corregido por inspección visual.',
    resolved: true,
  },
  {
    id: 'dq2',
    variable_id: 'v3',
    variable_name: 'Temperatura Hormigón',
    issue_type: 'not_received',
    original_value: null,
    corrected_value: 18.2,
    user: 'Técnico Auscultación',
    date: '12/05/2026 09:30',
    reason: 'Sin dato desde DAMDATA en ventana de 30 min. Introducido manualmente tras lectura directa del sensor TERM-003.',
    resolved: true,
  },
];
