import type {
  Indicator, EmergencyAction, Recipient, CommunicationRecord, TimelineEvent, EmergencyState,
} from './types';

export const MOCK_INDICATORS: Indicator[] = [
  { id: 'i1', name: 'Nivel de embalse',     value: '383,95 m',        threshold: '383,50 m', evaluation: 'Cuantitativa', status: 'superado',             unit: 'm',    cause: 'hidrologica' },
  { id: 'i2', name: 'Caudal entrante',       value: '480 m³/s',        threshold: '450 m³/s', evaluation: 'Cuantitativa', status: 'superado',             unit: 'm³/s', cause: 'hidrologica' },
  { id: 'i3', name: 'Precipitación 24h',     value: '74 mm',           threshold: '70 mm',    evaluation: 'Cuantitativa', status: 'superado',             unit: 'mm',   cause: 'hidrologica' },
  { id: 'i4', name: 'Piezómetro P-07',       value: '43,2 m',          threshold: '48,0 m',   evaluation: 'Cuantitativa', status: 'normal',               unit: 'm',    cause: 'auscultacion' },
  { id: 'i5', name: 'Aceleración sísmica',   value: '0,008 g',         threshold: '0,05 g',   evaluation: 'Cuantitativa', status: 'normal',               unit: 'g',    cause: 'sismo' },
  { id: 'i6', name: 'Inspección visual',     value: 'En curso',        threshold: '—',        evaluation: 'Cualitativa',  status: 'pendiente_validacion',               cause: 'inspeccion' },
  { id: 'i7', name: 'Estado sirenas',        value: '8/10 operativas', threshold: '—',        evaluation: 'Cualitativa',  status: 'normal',                             cause: 'equipos_aviso' },
  { id: 'i8', name: 'Presa aguas arriba',    value: 'Sin novedad',     threshold: '—',        evaluation: 'Cualitativa',  status: 'normal',                             cause: 'presa_aguas_arriba' },
];

// ── Actuaciones — Escenario 0 (Bembézar) ───────────────────────────────────

export const MOCK_ACTIONS_ESC0: EmergencyAction[] = [
  {
    id: 'a1', num: 1,
    name: 'Vigilancia permanente del nivel del embalse y caudales',
    responsible: 'Adjunto/a al Director/a del Plan',
    procedure: 'PV-1',
    personnel: 'Auxiliar de Auscultación (turno reforzado)',
    resources: 'Equipo SAIH, limnígrafos, teléfono de guardia',
    type: 'inspeccion',
    status: 'en_curso',
    startedAt: '09:18',
    observations: 'Lecturas SAIH cada 15 min. Nivel actual 383,95 m. Tendencia al alza +0,12 m/h.',
  },
  {
    id: 'a2', num: 2,
    name: 'Inspección visual de la presa, aliviadero y zona de pie de presa',
    responsible: 'Jefe/a de Inspección y Equipos',
    procedure: 'PV-2',
    personnel: 'Auxiliar de Auscultación + Auxiliar de Equipos',
    resources: 'EPIs, linterna, ficha de inspección F-3, vehículo 4x4',
    type: 'inspeccion',
    status: 'en_curso',
    startedAt: '09:25',
    observations: 'Primera pasada completada sin anomalías estructurales visibles. Segunda pasada en curso por coronación.',
  },
  {
    id: 'a3', num: 3,
    name: 'Prueba de operatividad de desagüe de fondo y toma hidroeléctrica',
    responsible: 'Jefe/a de Inspección y Equipos',
    procedure: 'PV-6',
    personnel: 'Auxiliar de Equipos',
    resources: 'Panel HMI sala de control, sistema SCADA, equipo de comunicación',
    type: 'ejecucion',
    status: 'realizada',
    startedAt: '09:30',
    completedAt: '09:47',
    observations: 'Desagüe de fondo: apertura parcial al 30% sin incidencias. Caudal evacuado 12,4 m³/s. Toma hidroeléctrica operativa.',
  },
  {
    id: 'a4', num: 4,
    name: 'Prueba de arranque grupos electrógenos de emergencia',
    responsible: 'Jefe/a de Inspección y Equipos',
    procedure: 'PV-7',
    personnel: 'Auxiliar de Equipos',
    resources: 'Grupos electrógenos GE-01 y GE-02, cuadro de conmutación',
    type: 'ejecucion',
    status: 'realizada',
    startedAt: '09:35',
    completedAt: '09:42',
    observations: 'GE-01 arrancado correctamente (30 kVA). GE-02 arrancado correctamente (30 kVA). Ambos en modo automático.',
  },
  {
    id: 'a5', num: 5,
    name: 'Notificación al Director/a del Plan de Emergencia',
    responsible: 'Adjunto/a al Director/a del Plan',
    procedure: 'PC-1',
    personnel: 'Auxiliar de Comunicaciones',
    resources: 'Teléfono, correo electrónico institucional',
    type: 'ejecucion',
    status: 'realizada',
    startedAt: '09:12',
    completedAt: '09:14',
    observations: 'Contacto confirmado con D. José García Morales (Director del Plan). Informado de superación de umbrales E0. Autoriza declaración.',
  },
  {
    id: 'a6', num: 6,
    name: 'Activación del sistema de auscultación automática en modo alerta',
    responsible: 'Adjunto/a al Director/a del Plan',
    procedure: 'PV-3',
    personnel: 'Auxiliar de Auscultación',
    resources: 'SCADA SIPRESAS, red de 12 piezómetros, 4 extensómetros, aforadores',
    type: 'ejecucion',
    status: 'realizada',
    startedAt: '09:14',
    completedAt: '09:16',
    observations: 'Sistema activado en modo alerta E0. Frecuencia de lectura reducida a 15 min. 11/12 piezómetros operativos (P-07 con sensor en revisión).',
  },
  {
    id: 'a7', num: 7,
    name: 'Preparación del aliviadero de superficie para posible apertura',
    responsible: 'Jefe/a de Inspección y Equipos',
    procedure: 'PV-4',
    personnel: 'Auxiliar de Equipos + Auxiliar de Auscultación',
    resources: 'Sistemas de accionamiento compuertas, equipo de comunicación portátil',
    type: 'ejecucion',
    status: 'pendiente',
    observations: 'En espera de instrucción del Director del Plan. Umbral de activación: nivel > 384,50 m.',
  },
  {
    id: 'a8', num: 8,
    name: 'Verificación de vías de evacuación aguas abajo (Hornachuelos, Palma del Río)',
    responsible: 'Adjunto/a al Director/a del Plan',
    procedure: 'PC-3',
    personnel: 'Auxiliar de Comunicaciones',
    resources: 'Contacto directo Protección Civil Córdoba, mapas de inundabilidad',
    type: 'inspeccion',
    status: 'pendiente',
    observations: 'Pendiente de coordinación con 112 Andalucía. Activar si se declara Escenario 1.',
  },
];

// ── Destinatarios de comunicación ──────────────────────────────────────────

export const MOCK_RECIPIENTS: Recipient[] = [
  { id: 'r1', name: 'Centro de Control de Sevilla / SAIH Guadalquivir', role: 'Organismo de cuenca',  email: 'saih.guadalquivir@chguadalquivir.es',    selected: true,  required: true },
  { id: 'r2', name: 'Jefe/a del Área de Explotación CHG',               role: 'Responsable interno',  email: 'explotacion@chguadalquivir.es',          selected: true,  required: true },
  { id: 'r3', name: 'Comité Permanente de la CHG',                      role: 'Órgano directivo',     email: 'comite.permanente@chguadalquivir.es',    selected: true,  required: true },
  { id: 'r4', name: '112 Andalucía — Emergencias',                      role: 'Protección Civil',     email: 'emergencias112@juntadeandalucia.es',     selected: true,  required: false },
  { id: 'r5', name: 'Dirección General del Agua — MITECO',              role: 'Administración central', email: 'dga@miteco.gob.es',                  selected: false, required: false },
  { id: 'r6', name: 'Jefe/a Guardia Civil Puesto Hornachuelos',         role: 'Seguridad',            email: 'guardia.civil.hornachuelos@mir.es',      selected: true,  required: false },
  { id: 'r7', name: 'Ayuntamiento de Hornachuelos',                     role: 'Administración local', email: 'alcaldia@hornachuelos.es',               selected: true,  required: false },
  { id: 'r8', name: 'Ayuntamiento de Palma del Río',                    role: 'Administración local', email: 'alcaldia@palmadelrio.es',                selected: false, required: false },
  { id: 'r9', name: 'Delegación del Gobierno en Andalucía',             role: 'Administración',       email: 'delegacion.andalucia@mpr.gob.es',        selected: false, required: false },
];

export const MOCK_COMMS: CommunicationRecord[] = [
  { id: 'c1', recipient: 'Centro de Control Sevilla / SAIH Guadalquivir', method: 'Correo electrónico', sentAt: '09:20', ackAt: '09:31', status: 'acuse_recibido' },
  { id: 'c2', recipient: 'Jefe/a del Área de Explotación CHG',            method: 'Correo electrónico', sentAt: '09:20', ackAt: '09:28', status: 'acuse_recibido' },
  { id: 'c3', recipient: 'Comité Permanente de la CHG',                   method: 'Correo electrónico', sentAt: '09:20',               status: 'enviado' },
  { id: 'c4', recipient: '112 Andalucía — Emergencias',                   method: 'Correo electrónico', sentAt: '09:21', ackAt: '09:26', status: 'acuse_recibido' },
  { id: 'c5', recipient: 'Jefe/a Guardia Civil Puesto Hornachuelos',      method: 'Correo electrónico', sentAt: '09:21',               status: 'enviado' },
  { id: 'c6', recipient: 'Ayuntamiento de Hornachuelos',                  method: 'Correo electrónico', sentAt: '09:21',               status: 'enviado' },
];

// ── Registro / Línea de tiempo ─────────────────────────────────────────────

export const MOCK_TIMELINE: TimelineEvent[] = [
  {
    id: 't1', time: '09:08', type: 'sistema',
    event: 'Alerta automática: nivel embalse supera umbral E0 (383,95 m > 383,50 m)',
    user: 'Sistema SIPRESAS — SAIH Guadalquivir',
    result: 'Propuesta de Escenario 0 generada automáticamente',
  },
  {
    id: 't2', time: '09:09', type: 'sistema',
    event: 'Alerta automática: caudal entrante supera umbral E0 (480 m³/s > 450 m³/s)',
    user: 'Sistema SIPRESAS — Estación EA-079 Bembézar',
    result: 'Propuesta E0 reforzada — Confianza: Alta',
  },
  {
    id: 't3', time: '09:10', type: 'sistema',
    event: 'Alerta automática: precipitación acumulada 24h supera umbral (74 mm > 70 mm)',
    user: 'Sistema SIPRESAS — Pluviómetro PL-BEM-01',
    result: '3 indicadores hidrológicos superados — Causa confirmada',
  },
  {
    id: 't4', time: '09:12', type: 'actuacion',
    event: 'Notificación al Director del Plan — Procedimiento PC-1 iniciado',
    user: 'Aux. Comunicaciones — M. Ruiz Sánchez',
    result: 'Contacto establecido con D. José García Morales',
  },
  {
    id: 't5', time: '09:14', type: 'decision',
    event: 'Director del Plan revisa propuesta de Escenario 0 y acepta declaración',
    user: 'Dir. del Plan — J. García Morales',
    result: 'Propuesta aceptada. Autoriza declaración E0',
  },
  {
    id: 't6', time: '09:17', type: 'decision',
    event: 'DECLARADO Escenario 0 — Causa: Eventos hidrológicos (lluvia + caudal + nivel)',
    user: 'Dir. del Plan — J. García Morales',
    result: 'Emergencia activa · Escenario 0 · Bembézar (GQ-009)',
  },
  {
    id: 't7', time: '09:18', type: 'actuacion',
    event: 'PV-1 iniciada: vigilancia permanente nivel embalse activada (frecuencia 15 min)',
    user: 'Aux. Auscultación — F. López Pérez',
    result: 'En curso — Siguiente lectura: 09:33',
  },
  {
    id: 't8', time: '09:20', type: 'comunicacion',
    event: 'Comunicación F-2 enviada a 6 destinatarios (formulario oficial E0)',
    user: 'Aux. Comunicaciones — M. Ruiz Sánchez',
    result: 'Pendiente de acuse de recibo',
  },
  {
    id: 't9', time: '09:21', type: 'actuacion',
    event: 'PV-3 activada: sistema auscultación automática en modo alerta E0',
    user: 'Aux. Auscultación — F. López Pérez',
    result: 'Realizada — 11/12 sensores activos · P-07 en revisión preventiva',
  },
  {
    id: 't10', time: '09:25', type: 'actuacion',
    event: 'PV-2 iniciada: inspección visual de coronación, talud aguas abajo y pie de presa',
    user: 'Jefe/a Inspección — A. Montero Díaz',
    result: 'En curso — Sin anomalías en primera pasada',
  },
  {
    id: 't11', time: '09:26', type: 'comunicacion',
    event: 'Acuse de recibo — 112 Andalucía confirma recepción comunicación E0',
    user: 'Sistema (email automático)',
    result: 'Confirmado por 112 Andalucía a las 09:26',
  },
  {
    id: 't12', time: '09:28', type: 'comunicacion',
    event: 'Acuse de recibo — Jefe/a Área Explotación CHG confirma recepción',
    user: 'Sistema (email automático)',
    result: 'Confirmado — Acuse automático',
  },
  {
    id: 't13', time: '09:30', type: 'actuacion',
    event: 'PV-6 iniciada: prueba operatividad desagüe de fondo y toma hidroeléctrica',
    user: 'Aux. Equipos — R. Fernández Vega',
    result: 'En curso — Apertura parcial 30%',
  },
  {
    id: 't14', time: '09:31', type: 'comunicacion',
    event: 'Acuse de recibo — Centro de Control Sevilla / SAIH Guadalquivir',
    user: 'Sistema (email automático)',
    result: 'Confirmado · SAIH inicia monitorización reforzada cuenca Bembézar',
  },
  {
    id: 't15', time: '09:35', type: 'actuacion',
    event: 'PV-7 iniciada: arranque y prueba grupos electrógenos GE-01 y GE-02',
    user: 'Aux. Equipos — R. Fernández Vega',
    result: 'En curso — Ambos grupos respondiendo',
  },
  {
    id: 't16', time: '09:42', type: 'actuacion',
    event: 'PV-7 completada: GE-01 y GE-02 operativos en modo automático',
    user: 'Aux. Equipos — R. Fernández Vega',
    result: 'Realizada — Suministro eléctrico de respaldo garantizado',
  },
  {
    id: 't17', time: '09:47', type: 'actuacion',
    event: 'PV-6 completada: desagüe de fondo operativo (12,4 m³/s evacuados)',
    user: 'Aux. Equipos — R. Fernández Vega',
    result: 'Realizada — Caudal de control establecido',
  },
  {
    id: 't18', time: '09:55', type: 'sistema',
    event: 'Actualización automática indicadores: nivel embalse 383,97 m (+0,02 m en 47 min)',
    user: 'Sistema SIPRESAS — SAIH',
    result: 'Tendencia alcista moderada. Sin cambio de escenario.',
  },
];

export const INITIAL_EMERGENCY_STATE: EmergencyState = {
  scenario: 'escenario_0',
  cause: 'hidrologica',
  proposedScenario: 'escenario_0',
  proposedCause: 'hidrologica',
  proposedConfidence: 'alta',
  declaredAt: '09:17',
  declaredBy: 'J. García Morales — Director del Plan',
  declarationReason: 'Superación simultánea de tres umbrales hidrológicos: nivel embalse (383,95 m > 383,50 m), caudal entrante (480 m³/s > 450 m³/s) y precipitación 24h (74 mm > 70 mm). Situación en evolución con tendencia alcista.',
  active: true,
};
