import type {
  BimElement, BimModel, BimAlert, BimHistoricEvent, BimAuditEntry
} from './types';

export const CURRENT_DATE = '19/05/2026';
export const DAM_NAME = 'Presa de Guadalmena';
export const DAM_CODE = 'GQ-012';

// ─── BIM Elements (SVG cross-section of Guadalmena dam) ─────────────────────

export const BIM_ELEMENTS: BimElement[] = [
  // --- Body / Structure ---
  {
    id: 'E-001',
    code: 'EST-CUE-001',
    name: 'Cuerpo de Presa',
    category: 'structure',
    status: 'operational',
    x: 120, y: 160, width: 360, height: 200,
    svgType: 'polygon',
    points: '120,360 200,160 400,160 480,360',
    layer: ['inventory', 'maintenance', 'exploitation'],
    inventory_ref: 'INV-EST-001',
    maintenance_last_date: '14/03/2026',
    maintenance_last_pdf: 'informe_inspeccion_cuerpo_presa.pdf',
    maintenance_next_date: '14/09/2026',
    maintenance_status: 'Al día',
    exploitation_status: 'S. Extraordinaria activa',
    archive_docs: 12,
    criticality: 'critical',
    description: 'Cuerpo principal de la presa de gravedad de hormigón. Altura 78m, longitud de coronación 380m.',
    material: 'Hormigón en masa CEM I 42.5',
    dimensions: 'H=78m · L=380m · Volumen=1.2 Mm³',
    last_inspection: '02/04/2026',
  },
  // --- Crown ---
  {
    id: 'E-002',
    code: 'EST-COR-001',
    name: 'Coronación',
    category: 'structure',
    status: 'operational',
    x: 195, y: 150, width: 210, height: 20,
    svgType: 'rect',
    layer: ['inventory', 'maintenance'],
    inventory_ref: 'INV-EST-002',
    maintenance_last_date: '20/01/2026',
    maintenance_next_date: '20/07/2026',
    maintenance_status: 'Al día',
    archive_docs: 5,
    criticality: 'medium',
    description: 'Coronación de la presa. Cota 610.00m. Ancho 8.5m. Vía de servicio y acceso a equipos.',
    material: 'Hormigón armado',
    dimensions: 'Cota 610.00m · Ancho 8.5m · L=380m',
    last_inspection: '20/01/2026',
  },
  // --- Spillway ---
  {
    id: 'E-003',
    code: 'ORG-ALI-001',
    name: 'Aliviadero de superficie',
    category: 'organ',
    status: 'operational',
    x: 270, y: 140, width: 60, height: 30,
    svgType: 'rect',
    layer: ['inventory', 'maintenance', 'exploitation'],
    inventory_ref: 'INV-ORG-003',
    maintenance_last_date: '05/05/2026',
    maintenance_last_pdf: 'informe_revision_aliviadero.pdf',
    maintenance_next_date: '05/11/2026',
    maintenance_status: 'Al día',
    exploitation_status: 'Operativo · Q=180 m³/s',
    archive_docs: 8,
    criticality: 'critical',
    description: 'Aliviadero de labio fijo en coronación. Cota umbral 607.00m. Capacidad máx. 1.850 m³/s.',
    material: 'Hormigón armado revestido',
    dimensions: 'Umbral 607.00m · L=45m · Qmax=1850 m³/s',
    last_inspection: '05/05/2026',
  },
  // --- Bottom outlet ---
  {
    id: 'E-004',
    code: 'ORG-DES-001',
    name: 'Desagüe de fondo',
    category: 'organ',
    status: 'revision_pending',
    x: 165, y: 300, width: 50, height: 30,
    svgType: 'rect',
    layer: ['inventory', 'maintenance', 'exploitation'],
    inventory_ref: 'INV-ORG-004',
    maintenance_last_date: '10/02/2026',
    maintenance_last_pdf: 'informe_desague_fondo.pdf',
    maintenance_next_date: '10/05/2026',
    maintenance_status: 'Revision pendiente · OT-2026-018',
    exploitation_status: 'Cerrado · Revisión programada',
    archive_docs: 6,
    criticality: 'critical',
    description: 'Desagüe de fondo DN-1200 con válvulas de guarda y regulación. Cota eje 535.00m.',
    material: 'Acero inoxidable AISI 316',
    dimensions: 'DN=1200mm · Cota eje 535.00m · Qmax=85 m³/s',
    last_inspection: '10/02/2026',
  },
  // --- Mid-level outlet ---
  {
    id: 'E-005',
    code: 'ORG-DES-002',
    name: 'Desagüe intermedio',
    category: 'organ',
    status: 'operational',
    x: 165, y: 240, width: 50, height: 28,
    svgType: 'rect',
    layer: ['inventory', 'maintenance', 'exploitation'],
    inventory_ref: 'INV-ORG-005',
    maintenance_last_date: '01/04/2026',
    maintenance_next_date: '01/10/2026',
    maintenance_status: 'Al día',
    exploitation_status: 'Operativo · Abierto al 60%',
    archive_docs: 5,
    criticality: 'high',
    description: 'Desagüe intermedio DN-800. Cota eje 562.00m. Compuerta deslizante motorizada.',
    material: 'Acero al carbono pintado',
    dimensions: 'DN=800mm · Cota eje 562.00m · Qmax=48 m³/s',
    last_inspection: '01/04/2026',
  },
  // --- Piezometer P-14 ---
  {
    id: 'E-006',
    code: 'AUS-PIE-014',
    name: 'Piezómetro P-14',
    category: 'sensor',
    status: 'threshold_exceeded',
    x: 280, y: 270, width: 20, height: 20,
    svgType: 'ellipse',
    layer: ['auscultation'],
    auscultation_variable: 'Presión intersticial P-14',
    auscultation_value: '2.18',
    auscultation_unit: 'kg/cm²',
    auscultation_threshold: '2.00',
    auscultation_status: 'Umbral S.E. superado',
    archive_docs: 3,
    criticality: 'critical',
    description: 'Piezómetro de tubo abierto en cuerpo de presa. Mide presión intersticial en zona central.',
    dimensions: 'Prof. 45m · Cota instalación 565.00m',
    last_inspection: '15/05/2026',
  },
  // --- Total Seepage Sensor ---
  {
    id: 'E-007',
    code: 'AUS-FIL-001',
    name: 'Medidor filtración total',
    category: 'instrumentation',
    status: 'threshold_exceeded',
    x: 440, y: 310, width: 24, height: 24,
    svgType: 'ellipse',
    layer: ['auscultation'],
    auscultation_variable: 'Filtración Total',
    auscultation_value: '212.7',
    auscultation_unit: 'l/s',
    auscultation_threshold: '169.1',
    auscultation_status: 'S. Extraordinaria · Umbral superado 25.8%',
    archive_docs: 4,
    criticality: 'critical',
    description: 'Caudalímetro electromagnético para medición de filtración total aguas abajo.',
    dimensions: 'DN=200mm · Rango 0-500 l/s',
    last_inspection: '15/05/2026',
  },
  // --- Horizontal Displacement Pendulum ---
  {
    id: 'E-008',
    code: 'AUS-PEN-002',
    name: 'Péndulo directo P-D2',
    category: 'instrumentation',
    status: 'operational',
    x: 310, y: 200, width: 16, height: 16,
    svgType: 'ellipse',
    layer: ['auscultation'],
    auscultation_variable: 'Desplazamiento horizontal',
    auscultation_value: '3.2',
    auscultation_unit: 'mm',
    auscultation_threshold: '15.0',
    auscultation_status: 'Normal',
    archive_docs: 2,
    criticality: 'high',
    description: 'Péndulo directo para medición de desplazamientos horizontales en coronación.',
    dimensions: 'Rango ±50mm · Precisión 0.1mm',
    last_inspection: '15/05/2026',
  },
  // --- Gallery ---
  {
    id: 'E-009',
    code: 'EST-GAL-001',
    name: 'Galería de inspección',
    category: 'access',
    status: 'operational',
    x: 210, y: 290, width: 175, height: 20,
    svgType: 'rect',
    layer: ['inventory', 'maintenance'],
    inventory_ref: 'INV-EST-009',
    maintenance_last_date: '15/01/2026',
    maintenance_next_date: '15/07/2026',
    maintenance_status: 'Al día',
    archive_docs: 7,
    criticality: 'high',
    description: 'Galería perimetral de inspección. Cota 545.00m. Acceso a instrumentación y drenajes.',
    dimensions: 'Sección 2.0×2.5m · L=420m · Cota 545.00m',
    last_inspection: '15/01/2026',
  },
  // --- Electrical equipment ---
  {
    id: 'E-010',
    code: 'MEC-ELE-001',
    name: 'Cuadro eléctrico principal',
    category: 'mechanical',
    status: 'failure',
    x: 460, y: 155, width: 40, height: 32,
    svgType: 'rect',
    layer: ['inventory', 'maintenance'],
    inventory_ref: 'INV-MEC-010',
    maintenance_last_date: '18/05/2026',
    maintenance_last_pdf: 'averia_cuadro_electrico.pdf',
    maintenance_next_date: '20/05/2026',
    maintenance_status: 'AVERIA · OT urgente 2026-023',
    archive_docs: 3,
    criticality: 'high',
    description: 'Cuadro eléctrico principal de mando y protección de equipos de desagüe y aliviadero.',
    material: 'Acero inoxidable IP65',
    dimensions: 'Alimentación 400V/50Hz · 200kVA',
    last_inspection: '18/05/2026',
  },
  // --- Seismic sensor ---
  {
    id: 'E-011',
    code: 'AUS-SIS-001',
    name: 'Acelerógrafo sísmico',
    category: 'sensor',
    status: 'operational',
    x: 230, y: 158, width: 16, height: 16,
    svgType: 'ellipse',
    layer: ['auscultation', 'exploitation'],
    auscultation_variable: 'Aceleración sísmica',
    auscultation_value: '0.021',
    auscultation_unit: 'g',
    auscultation_threshold: '0.05',
    auscultation_status: 'Normal',
    archive_docs: 2,
    criticality: 'high',
    description: 'Acelerógrafo triaxial IGME-RED integrado. Mide aceleración en 3 ejes durante sismos.',
    dimensions: 'Rango ±2g · Precisión 0.001g · Integrado RED IGME',
    last_inspection: '15/04/2026',
  },
  // --- Reservoir level sensor ---
  {
    id: 'E-012',
    code: 'AUS-NIV-001',
    name: 'Limnígrafo SAIH',
    category: 'sensor',
    status: 'operational',
    x: 60, y: 220, width: 20, height: 20,
    svgType: 'ellipse',
    layer: ['auscultation', 'exploitation'],
    auscultation_variable: 'Nivel embalse',
    auscultation_value: '600.92',
    auscultation_unit: 'm.s.n.m.',
    auscultation_threshold: '607.00',
    auscultation_status: 'Normal · SAIH en línea',
    archive_docs: 1,
    criticality: 'critical',
    description: 'Limnígrafo SAIH-CHG para medición automática de nivel de embalse. Sincronizado en tiempo real.',
    dimensions: 'Rango 520-610m · Precisión 1cm · SAIH integrado',
    last_inspection: '01/05/2026',
  },
];

// ─── BIM Models ──────────────────────────────────────────────────────────────

export const BIM_MODELS: BimModel[] = [
  {
    id: 'M-001',
    name: 'Modelo BIM completo Guadalmena',
    description: 'Modelo integrado completo del cuerpo de presa, órganos de desagüe, galería y zona de pie.',
    format: 'IFC',
    state: 'published',
    version: '3.2',
    version_date: '12/03/2026',
    size_mb: 1240,
    elements_count: 14832,
    author: 'Carlos Fernández Ruiz',
    published_by: 'Ana García López',
    published_date: '20/03/2026',
    saih_sync: true,
    last_sync: '19/05/2026 07:30',
    changes_summary: 'Actualización coordenadas instrumentación, corrección galería bloque 7',
  },
  {
    id: 'M-002',
    name: 'Aliviadero y canal de descarga',
    description: 'Modelo detallado del aliviadero de superficie y canal de descarga hasta el río.',
    format: 'IFC',
    state: 'published',
    version: '2.1',
    version_date: '18/01/2026',
    size_mb: 385,
    elements_count: 3241,
    author: 'Laura Sánchez Molina',
    published_by: 'Ana García López',
    published_date: '25/01/2026',
    saih_sync: false,
    changes_summary: 'Revisión sección hidráulica compuertas',
  },
  {
    id: 'M-003',
    name: 'Instrumentación y auscultación',
    description: 'Modelo de posicionamiento exacto de todos los sensores, piezómetros, péndulos y aforos.',
    format: 'IFC',
    state: 'review',
    version: '1.4-rc',
    version_date: '07/05/2026',
    size_mb: 220,
    elements_count: 892,
    author: 'Miguel Torres Pérez',
    saih_sync: true,
    last_sync: '19/05/2026 07:30',
    changes_summary: 'Nuevo piezómetro P-18, actualización coordenadas P-14',
  },
  {
    id: 'M-004',
    name: 'Optimizado para visor web',
    description: 'Versión ligera del modelo completo optimizada para renderizado en navegador.',
    format: 'FBX',
    state: 'published',
    version: '3.2-lite',
    version_date: '14/03/2026',
    size_mb: 88,
    elements_count: 4200,
    author: 'Carlos Fernández Ruiz',
    published_by: 'Ana García López',
    published_date: '21/03/2026',
    saih_sync: false,
    changes_summary: 'Generado a partir de M-001 v3.2 con reducción de detalle nivel 3',
  },
  {
    id: 'M-005',
    name: 'Planos As-Built 2018',
    description: 'Digitalización de planos as-built originales de construcción.',
    format: 'DWG',
    state: 'obsolete',
    version: '1.0',
    version_date: '15/06/2018',
    size_mb: 145,
    elements_count: 1200,
    author: 'Archivo Técnico CHG',
    saih_sync: false,
    changes_summary: 'Digitalización inicial. Sustituido por modelo IFC v3.x',
  },
];

// ─── BIM Alerts ─────────────────────────────────────────────────────────────

export const BIM_ALERTS: BimAlert[] = [
  {
    id: 'BA-001',
    date: '19/05/2026',
    time: '07:45',
    element_id: 'E-010',
    element_name: 'Cuadro eléctrico principal',
    source: 'maintenance',
    severity: 'critical',
    title: 'Avería cuadro eléctrico principal',
    description: 'Fallo del módulo de protección diferencial. Orden de trabajo urgente OT-2026-023 generada. Sin alimentación a equipos de mando del desagüe de fondo.',
    resolved: false,
  },
  {
    id: 'BA-002',
    date: '18/05/2026',
    time: '23:12',
    element_id: 'E-007',
    element_name: 'Medidor filtración total',
    source: 'auscultation',
    severity: 'critical',
    title: 'Filtración total supera umbral S.E.',
    description: 'Filtración total = 212.7 l/s · Umbral S.E. = 169.1 l/s · Exceso: +43.6 l/s (+25.8%). Director/a de Explotación notificado.',
    resolved: false,
  },
  {
    id: 'BA-003',
    date: '17/05/2026',
    time: '14:30',
    element_id: 'E-006',
    element_name: 'Piezómetro P-14',
    source: 'auscultation',
    severity: 'warning',
    title: 'Presión intersticial P-14 supera umbral',
    description: 'P-14 = 2.18 kg/cm² · Umbral S.E. = 2.00 kg/cm². Tendencia ascendente en últimas 72h. Correlacionado con cota embalse 600.92m.',
    resolved: false,
  },
  {
    id: 'BA-004',
    date: '16/05/2026',
    time: '09:00',
    element_id: 'E-004',
    element_name: 'Desagüe de fondo',
    source: 'maintenance',
    severity: 'warning',
    title: 'Revisión periódica vencida',
    description: 'Revisión semestral del desagüe de fondo vencida el 10/05/2026. OT-2026-018 programada. Acceso pendiente de coordinación con explotación.',
    resolved: false,
  },
  {
    id: 'BA-005',
    date: '14/05/2026',
    time: '16:22',
    element_id: 'E-003',
    element_name: 'Aliviadero de superficie',
    source: 'exploitation',
    severity: 'info',
    title: 'Aliviadero en operación activa',
    description: 'S. Extraordinaria declarada. Aliviadero desaguando Q=180 m³/s por avenida de caudal pico Qp=1420 m³/s. Fase de laminación activa.',
    resolved: false,
  },
  {
    id: 'BA-006',
    date: '10/05/2026',
    time: '11:15',
    element_id: 'E-001',
    element_name: 'Cuerpo de Presa',
    source: 'maintenance',
    severity: 'info',
    title: 'Inspección semestral completada',
    description: 'Inspección visual completa del paramento aguas arriba y abajo realizada. Sin anomalías estructurales detectadas. Informe PDF generado.',
    resolved: true,
    resolved_date: '10/05/2026',
    resolved_by: 'Carmen Rodríguez',
  },
];

// ─── Historic Events ─────────────────────────────────────────────────────────

export const BIM_HISTORIC: BimHistoricEvent[] = [
  { id: 'BH-001', date: '19/05/2026', time: '08:30', element_id: 'E-010', element_name: 'Cuadro eléctrico principal', event_type: 'status_changed', user: 'Admin Sistema', role: 'sipresas_admin', description: 'Estado cambiado a Avería (fallo módulo diferencial)', module: 'Mantenimiento' },
  { id: 'BH-002', date: '19/05/2026', time: '07:45', element_id: 'E-007', element_name: 'Medidor filtración total', event_type: 'alert_generated', user: 'Sistema DAMDATA', role: 'sipresas_admin', description: 'Alerta crítica generada: filtración 212.7 l/s > umbral 169.1 l/s', module: 'Auscultación' },
  { id: 'BH-003', date: '18/05/2026', time: '15:00', element_id: undefined, element_name: undefined, event_type: 'model_updated', user: 'Carlos Fernández', role: 'bim_admin', description: 'Modelo IFC M-003 actualizado a v1.4-rc. Nueva posición piezómetro P-18.', module: 'Modelos BIM' },
  { id: 'BH-004', date: '17/05/2026', time: '14:30', element_id: 'E-006', element_name: 'Piezómetro P-14', event_type: 'threshold_exceeded', user: 'Sistema DAMDATA', role: 'sipresas_admin', description: 'Umbral S.E. superado: 2.18 kg/cm² > 2.00 kg/cm²', module: 'Auscultación' },
  { id: 'BH-005', date: '15/05/2026', time: '10:00', element_id: 'E-009', element_name: 'Galería de inspección', event_type: 'maintenance_completed', user: 'Miguel Torres', role: 'maintenance_tech', description: 'Revisión limpieza sumideros galería completada. OT-2026-015 cerrada.', module: 'Mantenimiento' },
  { id: 'BH-006', date: '14/05/2026', time: '16:22', element_id: 'E-003', element_name: 'Aliviadero de superficie', event_type: 'status_changed', user: 'Ana García López', role: 'director', description: 'Aliviadero en operación activa por S.E. · Q=180 m³/s', module: 'Explotación' },
  { id: 'BH-007', date: '12/05/2026', time: '09:15', element_id: undefined, element_name: undefined, event_type: 'model_published', user: 'Ana García López', role: 'bim_admin', description: 'Modelo M-004 (visor web optimizado) publicado. Disponible para todos los usuarios.', module: 'Modelos BIM' },
  { id: 'BH-008', date: '10/05/2026', time: '11:15', element_id: 'E-001', element_name: 'Cuerpo de Presa', event_type: 'maintenance_completed', user: 'Carmen Rodríguez', role: 'maintenance_tech', description: 'Inspección semestral completada. Sin anomalías. Alerta BA-006 resuelta.', module: 'Mantenimiento' },
  { id: 'BH-009', date: '08/05/2026', time: '17:00', element_id: 'E-005', element_name: 'Desagüe intermedio', event_type: 'status_changed', user: 'Ana García López', role: 'director', description: 'Compuerta abierta al 60% para laminación de avenida. S.E. activa.', module: 'Explotación' },
  { id: 'BH-010', date: '05/05/2026', time: '14:00', element_id: 'E-003', element_name: 'Aliviadero de superficie', event_type: 'document_accessed', user: 'Laura Sánchez', role: 'viewer', description: 'Planos constructivos del aliviadero descargados desde Archivo Técnico.', module: 'Archivo Técnico' },
];

// ─── Audit Entries ────────────────────────────────────────────────────────────

export const BIM_AUDIT: BimAuditEntry[] = [
  { id: 'AU-001', date: '19/05/2026', time: '08:35', action: 'Consulta elemento BIM', user: 'Ana García López', role: 'director', result: 'Ficha completa E-010 consultada', detail: 'Cuadro eléctrico principal: estado, mantenimiento, integración', hash: 'sha256:a1b2c3d4e5f6789012345678901234567890abcd' },
  { id: 'AU-002', date: '19/05/2026', time: '08:30', action: 'Cambio estado elemento', user: 'Admin Sistema', role: 'sipresas_admin', result: 'E-010 → Avería (failure)', detail: 'Origen: sincronización módulo Mantenimiento OT-2026-023', hash: 'sha256:b2c3d4e5f6789012345678901234567890abcde1' },
  { id: 'AU-003', date: '18/05/2026', time: '15:05', action: 'Actualización modelo BIM', user: 'Carlos Fernández', role: 'bim_admin', result: 'M-003 actualizado a v1.4-rc', detail: 'IFC cargado: 892 elementos · 220MB · Validación superada', hash: 'sha256:c3d4e5f6789012345678901234567890abcdef12' },
  { id: 'AU-004', date: '17/05/2026', time: '14:32', action: 'Alerta generada automática', user: 'Sistema DAMDATA', role: 'sipresas_admin', result: 'Alerta BA-003 generada · E-006 P-14', detail: 'Sincronización módulo Auscultación · Valor 2.18 kg/cm²', hash: 'sha256:d4e5f6789012345678901234567890abcdef1234' },
  { id: 'AU-005', date: '14/05/2026', time: '16:25', action: 'Cambio estado elemento', user: 'Sistema Explotación', role: 'sipresas_admin', result: 'E-003 → Operativo (explotación activa)', detail: 'S.E. activa · Sincronización módulo Explotación', hash: 'sha256:e5f6789012345678901234567890abcdef123456' },
  { id: 'AU-006', date: '12/05/2026', time: '09:18', action: 'Publicación modelo BIM', user: 'Ana García López', role: 'bim_admin', result: 'M-004 publicado en entorno producción', detail: 'Firmado digitalmente · Disponible todos los roles', hash: 'sha256:f6789012345678901234567890abcdef12345678' },
  { id: 'AU-007', date: '10/05/2026', time: '11:20', action: 'Resolución alerta', user: 'Carmen Rodríguez', role: 'maintenance_tech', result: 'Alerta BA-006 resuelta', detail: 'Motivo: inspección semestral completada sin anomalías', hash: 'sha256:789012345678901234567890abcdef1234567890' },
  { id: 'AU-008', date: '05/05/2026', time: '14:02', action: 'Descarga documento', user: 'Laura Sánchez', role: 'viewer', result: 'Plano aliviadero descargado (6.2MB)', detail: 'Origen Archivo Técnico · Documento AT-GQ-PLN-008', hash: 'sha256:012345678901234567890abcdef12345678901234' },
];
